In [37]:
# Import dependencies
import pandas as pd
import os
import matplotlib.pyplot as plt
from pathlib import Path

In [11]:
# List what is in directory
os.listdir('.')

['Untitled1.ipynb',
 '.DS_Store',
 'Untitled.ipynb',
 'resources',
 'Untitled2.ipynb',
 '.ipynb_checkpoints']

In [31]:
# Select which columns to keep
columns_to_keep = ['State',
                   'Year',
                   'Overall Homeless - Non-Hispanic/Non-Latino',
                   'Overall Homeless - Hispanic/Latino',
                   'Overall Homeless - White',
                   'Overall Homeless - Black or African American',
                   'Overall Homeless - Asian',
                   'Overall Homeless - American Indian or Alaska Native',
                   'Overall Homeless - Native Hawaiian or Other Pacific Islander',
                   'Overall Homeless - Multiple Races',
                   'Sheltered Total Homeless - Non-Hispanic/Non-Latino',
                   'Sheltered Total Homeless - Hispanic/Latino',
                   'Sheltered Total Homeless - White',
                   'Sheltered Total Homeless - Black or African American',
                   'Sheltered Total Homeless - Asian',
                   'Sheltered Total Homeless - American Indian or Alaska Native',
                   'Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander',
                   'Sheltered Total Homeless - Multiple Races']

In [32]:
# Filter by rows (only CA and TX)
df_2020 = pd.read_excel('resources/demostate.xlsx', sheet_name = "2020")
ca_tx_2020 = df_2020[(df_2020['State'] == 'CA') | (df_2020['State'] == 'TX')]
df_filtered_2020 = ca_tx_2020[columns_to_keep]
df_filtered_2020.head()

,State,Year,Overall Homeless - Non-Hispanic/Non-Latino,Overall Homeless - Hispanic/Latino,Overall Homeless - White,Overall Homeless - Black or African American,Overall Homeless - Asian,Overall Homeless - American Indian or Alaska Native,Overall Homeless - Native Hawaiian or Other Pacific Islander,Overall Homeless - Multiple Races,Sheltered Total Homeless - Non-Hispanic/Non-Latino,Sheltered Total Homeless - Hispanic/Latino,Sheltered Total Homeless - White,Sheltered Total Homeless - Black or African American,Sheltered Total Homeless - Asian,Sheltered Total Homeless - American Indian or Alaska Native,Sheltered Total Homeless - Native Hawaiian or Other Pacific Islander,Sheltered Total Homeless - Multiple Races
5,CA,2020.0,109582,51966,87439,49610,3240,6386,1784,13089,31672,16216,26133,16492,948,1417,520,2378
47,TX,2020.0,19684,7545,15778,10001,206,346,89,809,10078,3939,7180,6019,136,128,41,513

In [33]:
# Filter by rows (only CA and TX)
df_2020 = pd.read_excel('resources/demostate.xlsx', sheet_name = "2020")
ca_tx_2020 = df_2020[(df_2020['State'] == 'CA') | (df_2020['State'] == 'TX')]
df_filtered_2020 = ca_tx_2020[columns_to_keep]

df_2019 = pd.read_excel('resources/demostate.xlsx', sheet_name = "2019")
ca_tx_2019 = df_2019[(df_2019['State'] == 'CA') | (df_2019['State'] == 'TX')]
df_filtered_2019 = ca_tx_2019[columns_to_keep]

df_2018 = pd.read_excel('resources/demostate.xlsx', sheet_name = "2018")
ca_tx_2018 = df_2018[(df_2018['State'] == 'CA') | (df_2018['State'] == 'TX')]
df_filtered_2018 = ca_tx_2018[columns_to_keep]

df_2017 = pd.read_excel('resources/demostate.xlsx', sheet_name = "2017")
ca_tx_2017 = df_2017[(df_2017['State'] == 'CA') | (df_2017['State'] == 'TX')]
df_filtered_2017 = ca_tx_2017[columns_to_keep]

df_2016 = pd.read_excel('resources/demostate.xlsx', sheet_name = "2016")
ca_tx_2016 = df_2016[(df_2016['State'] == 'CA') | (df_2016['State'] == 'TX')]
df_filtered_2016 = ca_tx_2016[columns_to_keep]

df_2015 = pd.read_excel('resources/demostate.xlsx', sheet_name = "2015")
ca_tx_2015 = df_2015[(df_2015['State'] == 'CA') | (df_2015['State'] == 'TX')]
df_filtered_2015 = ca_tx_2015[columns_to_keep]

In [30]:
# Combine rows into a few datasheet
combined_data = pd.concat([df_filtered_2020, 
                           df_filtered_2019,
                           df_filtered_2018, 
                           df_filtered_2017, 
                           df_filtered_2016,
                           df_filtered_2015], ignore_index=True)

combined_data

,State,Year,Overall Homeless - Non-Hispanic/Non-Latino,Overall Homeless - Hispanic/Latino,Overall Homeless - White,Overall Homeless - Black or African American,Overall Homeless - Asian,Overall Homeless - American Indian or Alaska Native,Overall Homeless - Native Hawaiian or Other Pacific Islander,Overall Homeless - Multiple Races
0,CA,2020.0,109582,51966,87439,49610,3240,6386,1784,13089
1,TX,2020.0,19684,7545,15778,10001,206,346,89,809
2,CA,2019.0,103759,47519,82164,44086,2606,6797,2177,13448
3,TX,2019.0,18884,6964,14984,9622,202,245,77,718
4,CA,2018.0,88525,41447,72956,37770,2338,5391,1552,9965
5,TX,2018.0,18163,7147,14363,9664,181,315,60,727
6,CA,2017.0,90040,41492,68784,42282,2490,5663,1459,10854
7,TX,2017.0,16942,6606,13076,8928,253,325,68,898
8,CA,2016.0,85437,32705,67669,32434,1836,4179,1284,10740
9,TX,2016.0,17180,5942,12795,8143,233,843,79,1029
10,CA,2015.0,84183,31555,64340,32262,2146,4762,1225,11003
11,TX,2015.0,16750,6928,13713,8603,145,424,104,689

In [36]:
# Sort combined_data by like state
custom_order = ['CA', 'TX']
combined_data['State'] = pd.Categorical(combined_data['State'], categories=custom_order, ordered=True)
combined_data = combined_data.sort_values('State')
combined_data

,State,Year,Overall Homeless - Non-Hispanic/Non-Latino,Overall Homeless - Hispanic/Latino,Overall Homeless - White,Overall Homeless - Black or African American,Overall Homeless - Asian,Overall Homeless - American Indian or Alaska Native,Overall Homeless - Native Hawaiian or Other Pacific Islander,Overall Homeless - Multiple Races
0,CA,2020.0,109582,51966,87439,49610,3240,6386,1784,13089
2,CA,2019.0,103759,47519,82164,44086,2606,6797,2177,13448
4,CA,2018.0,88525,41447,72956,37770,2338,5391,1552,9965
6,CA,2017.0,90040,41492,68784,42282,2490,5663,1459,10854
8,CA,2016.0,85437,32705,67669,32434,1836,4179,1284,10740
10,CA,2015.0,84183,31555,64340,32262,2146,4762,1225,11003
1,TX,2020.0,19684,7545,15778,10001,206,346,89,809
3,TX,2019.0,18884,6964,14984,9622,202,245,77,718
5,TX,2018.0,18163,7147,14363,9664,181,315,60,727
7,TX,2017.0,16942,6606,13076,8928,253,325,68,898
9,TX,2016.0,17180,5942,12795,8143,233,843,79,1029
11,TX,2015.0,16750,6928,13713,8603,145,424,104,689

In [ ]:
# Bar Graph (maybe???)